# Generated by Django 4.1.7 on 2023-03-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_comment_body_alter_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='is_likes',
            new_name='is_like',
        ),
    ]
