# Generated by Django 4.1.7 on 2023-03-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repostsss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repost',
            name='repost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposttt', to='post.post'),
        ),
    ]
