# Generated by Django 4.1.7 on 2023-03-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_login_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
