# Generated by Django 4.1.7 on 2023-03-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
