# Generated by Django 4.1.7 on 2023-03-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
