# Generated by Django 4.1.7 on 2023-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
