# Generated by Django 4.1.7 on 2023-03-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
