# Generated by Django 4.1.7 on 2023-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
