# Generated by Django 4.1.7 on 2023-03-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_customuser_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
    ]
