# Generated by Django 4.1.7 on 2023-03-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_customuser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
