# Generated by Django 4.1.7 on 2023-03-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_profile_remove_customuser_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.IntegerField(default=0),
        ),
    ]
