# Generated by Django 4.1.7 on 2023-03-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_profile_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followw',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='account.profile'),
        ),
    ]
